server:
  port: 8080

spring:
  application:
    name: skyops-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/skyops}
    username: ${SPRING_DATASOURCE_USERNAME:skyops_user}
    password: ${SPRING_DATASOURCE_PASSWORD:SkyOps@123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.skyops.backend: INFO