name: SkyOps Clone Platform CI

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_DB: skyops
          POSTGRES_USER: skyops_user
          POSTGRES_PASSWORD: SkyOps@123

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U skyops_user -d skyops"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: backend

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Grant execute permission
        run: chmod +x mvnw

      - name: Build and Test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/skyops
          SPRING_DATASOURCE_USERNAME: skyops_user
          SPRING_DATASOURCE_PASSWORD: SkyOps@123
        run: ./mvnw clean verify

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t skyops-backend .

      - name: Tag Docker Image
        run: |
          docker tag skyops-backend:latest \
          ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push \
          ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}